WayfireWM/wayfire-plugins-extra

metadata/force-fullscreen.xml
metadata/meson.build
src/force-fullscreen.cpp
src/meson.build

This plugin facilitates a way to force fullscreen on applications that do not support it, or otherwise have problems with fullscreen. The fullscreen state is emulated by stretching the surface to the fullscreen dimensions or by rendering the surface centered with black borders if preserve aspect option is set. This is useful for programs that do not fullscreen properly or at all. For example, if you have an xwayland game that does not support resize or fullscreen, you can still use this plugin to run it fullscreen. Examples include dosbox and scummvm. This is primarily useful for xwayland views but can be used on any native non-desktop views that can be focused, as well.

Add force fullscreen plugin

---

src/background-view.cpp

Check for WF_HAS_CONFIG set by wayfire instead of checking wlroots
WLR_HAS_XWAYLAND since wayfire can be configured without xwayland
support.

background-view: Use wayfire config

---

src/force-fullscreen.cpp

Use correct signal structure for pre-moved event, even though they're currently identical.

Track wayfire signal name changes pt2

---

src/keycolor.cpp

This fixes inverted transform when using wrot.

keycolor: Don't invert matrix

---

src/follow-focus.cpp
src/water.cpp
src/workspace-names.cpp

Sending this commit here, I plan to make a change in core so that timers can be used to repeat actions in a certain time.
This means that the callback signature needs to be changed to bool, so that the timer knows whether to continue or not.
The Wayfire PR has not been merged yet, so this is not to be merged right now.

adapt timers to upstream wayfire changes

---

src/glib-main-loop.cpp
src/meson.build

This is a plugin which overrides Wayfire's main loop, and utilizes
Glib's one instead. It can be used in plugins like wf-gsettings,
autorotate-iio, etc, which don't need to roll their own event loop
or use threads at all.
Sample changes for autorotate so that it doesn't have its own loop:
<details>
```diff
diff --git a/src/autorotate-iio.cpp b/src/autorotate-iio.cpp
index bb0d5f6..c8e7076 100644
--- a/src/autorotate-iio.cpp
+++ b/src/autorotate-iio.cpp
@@ -9,10 +9,6 @@
#include <giomm/dbusconnection.h>
#include <giomm/dbuswatchname.h>
#include <giomm/dbusproxy.h>
-#include <giomm/init.h>
-
-#include <glibmm/main.h>
-#include <glibmm/init.h>
#include <map>
@@ -75,7 +71,7 @@ class WayfireAutorotateIIO : public wf::plugin_interface_t
wf::option_wrapper_t<bool> …
```

add glib-main-loop plugin

---

.gitmodules

I have moved the submodule windecor from marcusbritanicus/windecor to wayfireplugins/windecor. This PR updates the submodule path.
@soreau Since I did a git pull --recurse-submodules the submodule paths are also updated.

Update the path of windecor submodule

---

src/background-view.cpp

Since sticky concept introduction, setting role to desktop no longer causes the
surface to display on all workspaces. Setting the view sticky is required and
setting the role becomes a formality.

background-view: Set sticky bit so the view appears on all workspaces again

---

metadata/hinge.xml
metadata/meson.build
src/hinge.cpp
src/meson.build

Given a filename to a sensor device this plugin can disable keyboard and pointer inputs depending on the value read from the sensor. This is helpful in 2in1 convertible laptops when you want to use it in a 'tent' configuration for example.
I'm not well versed in C++, so please do suggest edits, if needed.

Added hinge detection plugin

---

src/network-keyboard/meson.build

These are now pulled in with wayfire.

network-keyboard: Drop wlroots and wf-config dependencies

---

src/follow-focus.cpp

This makes it work with e.g. virtual machines where mouse may cause pointer_motion_absolute events only.

follow-focus: also connect on pointer_motion_absolute events

---

src/focus-steal-prevent.cpp

We might have a dangling pointer without making sure the view is one of the views in the core list before using it.

fsp: Ensure focus view is valid

---

src/annotate.cpp
src/bench.cpp
src/focus-steal-prevent.cpp
src/follow-focus.cpp
src/hide-cursor.cpp
src/join-views.cpp
src/keycolor.cpp
src/mag.cpp
src/meson.build
src/view-shot.cpp
src/water.cpp
src/window-zoom.cpp
src/workspace-names.cpp

I have updated most of the plugins, force-fullscreen and background-view may need a bit more work, but I am not in the mood for them right now :)
In general, we need a proper solution for sticky views (which is needed for background-view), because currently Wayfire draws sticky views only on one workspace.
Layer-shell views are hacked to work, but not very well (for example blur does not work with wf-panel in Expo). I will be working on a fix for wayfire soon.
In the meantime, I figured it will likely be best to update the rest of the plugins so that people that want them can use them.
@soreau I am not sure whether you are available, so if you do not respond in a week, I will just merge this PR.

Update plugins for changes in Wayfire master

---

src/annotate.cpp
src/workspace-names.cpp

This allows annotate and workspace-names to render over e.g. fullscreen surfaces.

Set overlays

---

src/view-shot.cpp

Otherwise, disabling the plugin and running the binding will cause a crash.

view-shot: Remove activator binding on fini

---

src/bench.cpp

This was causing flickering problems after configuring an output.

bench: Don't call set_redraw_always

---

src/mag.cpp

This effectively disables animations when unloading the plugin with the mag window still enabled but it prevents wayfire from crashing. Also, unminimize view when activating, in case it was minimized.

mag: Fixup

---

src/bench.cpp

The damage hook is run after damage is accumulated, which we are using to determine framerate.

bench: Use damage hook instead of pre effect

---

src/force-fullscreen.cpp

- Fix black borders wrong offset in come client cases like wcm
- Fix no black background when preserve_aspect is set and transparent_behind_views is not

force-fullscreen: A few fixups

---

meson.build
src/meson.build

Fix build in NixOS
```
../src/focus-steal-prevent.cpp:28:10: fatal error: libevdev/libevdev.h: No such file or directory
28 | #include <libevdev/libevdev.h>
|          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

build: check dependency libevdev

---

src/background-view.cpp

If we don't do this and the view is killed or dies, new views might be matched and set unintentionally as a background view.

background-view: Disconnect pre-mapped handler after setting up view

---

src/follow-focus.cpp

follow-focus: check whether a focused view is there in the timer handler

---

metadata/focus-change.xml
metadata/meson.build
src/focus-change.cpp
src/meson.build

This plugin allows the user to cycle through views using keybindings. This is similar to features seen in tiling window managers except it doesn't rely on tiling functionality.
The plugin provides a fair few options adjustable to the user so they can tweak it to their liking. The code hasn't successfully been tested on multiple outputs, and potentially the code related to the 'cross-output' settings isn't working properly.

Feature focus change

---

src/glib-main-loop.cpp

I try to fix #240  with the patch, but it results in a segement fault.
I tested it in qemu with virgl.
The whole log: 
```
II 27-06-24 10:23:18.257 - [backend/drm/drm.c:1556] Scanning DRM connectors on /dev/dri/card1
II 27-06-24 10:23:18.257 - [backend/drm/drm.c:1607] Found connector 'Virtual-1'
II 27-06-24 10:23:18.257 - [backend/drm/drm.c:1632] 'Virtual-1' connected
II 27-06-24 10:23:18.257 - [backend/drm/drm.c:1440] Detected modes:
II 27-06-24 10:23:18.257 - [backend/drm/drm.c:1468]   1280x800 @ 74.994 Hz (preferred)
II 27-06-24 10:23:18.257 - [backend/drm/drm.c:1468]   5120x2160 @ 50.000 Hz 
II 27-06-24 10:23:18.257 - [backend/drm/drm.c:1468]   4096x2160 @ 50.000 Hz 
II 27-06-24 10:23:18.257 - [backend/drm/drm.c:1468]   3840x2160 @ 60.000 Hz 
II 27-06-24 10:23:18.257 - …
```

make glib loop play well with SIGINT/SIGTERM

---

.github/workflows/ci.yaml
metadata/extra-animations.xml
metadata/meson.build
src/extra-animations/blinds.hpp
src/extra-animations/helix.hpp
src/extra-animations/meson.build
src/extra-animations/plugin.cpp
src/extra-animations/shatter.hpp
src/extra-animations/vortex.hpp
src/meson.build

The extra-animations plugin adds four new animations - blinds, helix, shatter and vortex. It requires animate and extra-animations plugins to be enabled. Currently, the new animations will not show up in wcm animate plugin, the config file must be edited manually. However, the options for the animations can be adjusted in wcm extra animations plugin. The animations are valid for open and close animation options.

Add extra-animations plugin

---

.github/workflows/ci.yaml
meson.build
src/obs.cpp
src/pin-view.cpp
src/view-shot.cpp

This should update the plugins relying on json to match the switch to yyjson from the wayfire master branch. I also have changes for the filters submodule locally, but I can't figure out how to include them.
I called the variables for the optionals maybe_x and maybe_y, but maybe there's a nicer way to fix this.

json: switch to yyjson

---

metadata/workspace-names.xml
src/workspace-names.cpp

Currently, we can set custom names to workspaces. However, there is no corresponding option in the xml metadata file. This PR adds the option "names" of type "dynamic-list" with type-hint "dict". Corresponding changes are made in the workspace-names.cpp file as well.

Add option 'names' to workspace-names

---

src/annotate.cpp
src/bench.cpp
src/crosshair.cpp
src/extra-animations/blinds.hpp
src/extra-animations/helix.hpp
src/extra-animations/plugin.cpp
src/extra-animations/shatter.hpp
src/extra-animations/vortex.hpp
src/focus-change.cpp
src/focus-steal-prevent.cpp
src/force-fullscreen.cpp
src/hide-cursor.cpp
src/keycolor.cpp
src/mag.cpp
src/obs.cpp
src/showrepaint.cpp
src/showtouch.cpp
src/view-shot.cpp
src/water.cpp
src/window-zoom.cpp
src/workspace-names.cpp

https://github.com/WayfireWM/wayfire/pull/2613 introduced some changes to Wayfire's rendering API. Some plugins I ported to use render-agnostic APIs, where it was harder (or impossible) I left custom GL rendering.
Note: I have not tested all of the plugins, only a couple of them (annotate, showrepaint, crosshair, bench). I thought it would be a good first step to get the code compiling and then let users test and report issues found, as I have not used many of those plugins and am not looking forward to testing all of them :)
P.S. the PR seems massive with many lines changed, but actually most of the lines are changes in the indentation due to the replacement of `OpenGL::render_begin/end`.

update for new wayfire rendering API

---

src/extra-animations/blinds.hpp
src/extra-animations/helix.hpp
src/extra-animations/shatter.hpp
src/extra-animations/vortex.hpp
src/keycolor.cpp
src/obs.cpp
src/showtouch.cpp
src/water.cpp

This fixes various rendering oddities, such as unintentional wind in water and tearing in vortex animation.

plugins: s/mediump/highp/

---

src/workspace-names.cpp

The recent port discarded the alpha component, so the workspace names would never disappear. Fix this by using render_transformed_texture().

workspace-names: Fix stuck rendering on screen

---

src/showrepaint.cpp

Requires some APIs I will push together with the wlroots 0.19 release, so don't merge yet :)

showrepaint: use new render-agnostic APIs in core

---

meson.build
src/meson.build

Depending on wayfire is enough, since the plugin API abstracts the underlying json library implementation.
Fixes #276.

build: Don't depend on json directly

---

ipc-scripts/workspace-names-setter.py
src/workspace-names.cpp

This pull request adds `ipc-scripts/workspace-names-setter.py` which takes a single string argument and sets the workspace name for the currently focused output and workspace. Workspace-names plugin was modified to check registered options and make this work.

Add workspace-names setter script and update plugin to allow usage

---

src/extra-animations/melt.hpp

This fixes melt animation cut off at open beginning or close end, around the edges.

extra-animations: Fix melt clipping
