src/autorotate-iio.cpp

Returns bool for bindings, changed in wayfire c71d548.
Fixes #4.

autorotate-iio: Track core changes

---

metadata/background-view.xml
metadata/meson.build
src/background-view.cpp
src/meson.build

This plugin allows a way to start a client that will be configured to be a desktop background.

Add background view plugin

---

src/keycolor.cpp

Storing the program as a global variable causes wayfire to crash
when disabling an output and in general is bad practice. Here we
store the program as custom data which is attatched to core, since
we only need a single instance of the object. This let's us manage
it so that the lifetime begins with the first plugin instance and
ends with the last.

keycolor: Store program data on core

---

src/annotate.cpp
src/workspace-names.cpp

s/viewport-changed/workspace-changed/

Update erroneous signal name

---

src/autorotate-iio.cpp

This is from quite a long time ago, I have forgotten to push it upstream.

autorotate-iio: swap 90/270 transforms to match changes in wlroots

---

src/follow-focus.cpp

this implements a 'fringe' behaviour, where the threshold is essentially how much distance *FROM THE ENTRY POINT* we need to move before it's considered. Note that a proper fringe might be better, because if you move threshold points on the side of a window it will trigger
Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>

only compare distance with the first coords we get,

---

meson.build

bump version to 0.6.0

---

src/mag.cpp

mag: Don't invert Y since wlroots renderer does this for us now

---

src/annotate.cpp
src/autorotate-iio.cpp
src/force-fullscreen.cpp
src/mag.cpp
src/showrepaint.cpp
src/water.cpp

Changes to the activator signatures are coming to Wayfire.
They are however not yet merged so this PR shouldn't be merged immediately either.

adapt for upcoming changes in wayfire

---

metadata/meson.build
metadata/window-zoom.xml
src/meson.build
src/window-zoom.cpp

Add window zoom plugin

---

src/force-fullscreen.cpp

Introduced by a change in core, rework things to make it not crash
when closing a view.

force-fullscreen: Fix crash when closing fullscreened surfaces

---

metadata/meson.build
metadata/view-shot.xml
src/meson.build
src/view-shot.cpp

This plugin allows taking screenshots of views.
Requires [this wayfire patch](https://github.com/WayfireWM/wayfire/pull/1146).

Add view shot plugin

---

src/mag.cpp

This reverts commit b089975de1bb80479039cdd1ebe5f6a1d2cd08c3.

Revert "mag: Don't invert Y since wlroots renderer does this for us now (#58)"

---

src/annotate.cpp

Before we were rendering and uploading to gpu on each motion event.
Now we do it only once per frame, which makes things much faster.

Make annotate faster

---

src/annotate.cpp

Only upload to the gpu what is strictly needed, instead of the entire framebuffer each frame.

annotate: Use glTexSubImage2D for less resource usage

---

src/annotate.cpp

Thanks to ericonr for pointing out this bug.

annotate: Fix GL errors

---

meson.build
metadata/hide-cursor.xml
metadata/meson.build
src/hide-cursor.cpp
src/meson.build

Add hide-cursor plugin

---

metadata/workspace-names.xml
src/workspace-names.cpp

Hopefully this is alright, please let me know if there's anything I've forgotten etc.

workspace-names settings: margin and background radius

---

src/workspace-names.cpp

Fix uncrustify issue with workspace_names.cpp
@soreau I'll update 116 after this is merged.

Uncrustify workspace_names.cpp

---

.github/workflows/ci.yaml
src/mag.cpp

I have not yet tested the mag plugin. I simply copied the mag.cpp from git to this branch and checked if it compiles.
If @magthe tests this, I believe we can merge. Otherwise, I will test it this weekend, after which we can merge.

Update mag.cpp to work with wlroots 0.15.1

---

src/background-view.cpp

background-view: Drop pid matching in favor of application identification

---

src/mag.cpp

Crash fixed in wayfire, updated to work with latest wayfire changes.

mag: Fixup

---

src/mag.cpp

Initialize variable to fix window stuck at 1x1 for random sessions.

mag: A minor fixup

---

.github/workflows/ci.yaml
src/force-fullscreen.cpp
src/window-zoom.cpp

Track wayfire changes

---

src/view-shot.cpp

Patch by @soreau to fix the inverted image while taking view snapshot

BugFix: fix inverted image when storing view snapshot

---

src/background-view.cpp

Discards all input for the background layer. This is made possible by a new feature in wayfire 07db3e76. Fixes #81. Closes #39.

background-view: Grab input for background layer

---

metadata/background-view.xml
src/background-view.cpp

Update bg view

---

metadata/bench.xml
src/bench.cpp

We were updating timing in the pre render hook but this was giving incorrect results.

bench: Update for better experience

---

src/background-view.cpp

This way, most apps should work without having to set an app_id manually.

background-view: Try to match using pid before checking app_id

---

src/background-view.cpp

Disconnect the pre_map handler after all outputs have been handled

background-view: Disconnect the pre_map handler after all outputs have been handled

---

src/focus-steal-prevent.cpp

fsp: Fix signal

---

metadata/meson.build

Install the focus-steal-prevent.xml

Fix focus-steal-prevent crash

---

src/focus-change.cpp

Adds some additional nullptr checks. This prevents crashing on my machine when no windows are present (why did I not test this???)

added additional nullptr checks preventing crash when no windows

---

src/workspace-names.cpp

Soreau's fix for workspace labels not hiding.

BugFix for workspace labels not hiding

---

src/view-shot.cpp

Adds ability for ipc scripts to take screenshots of views to specified locations.

view-shot: add ipc support

---

meson.build
meson_options.txt

Optionally build with -Denable_pixdecor=true -Denable_filters=true

Fixup pixdecor and filters submodules

---

metadata/ghost.xml
metadata/meson.build
src/ghost.cpp
src/meson.build

Allows windows to become click-through.

Add ghost plugin

---

src/obs.cpp

Thanks to s0ulslack for identifying the problem.

obs: Fix memory leaks

---

src/autorotate-iio.cpp
src/bench.cpp
src/focus-steal-prevent.cpp
src/follow-focus.cpp
src/glib-main-loop.cpp
src/hide-cursor.cpp
src/mag.cpp
src/showtouch.cpp
src/workspace-names.cpp

Recent wayfire refactoring moved around includes. Adding them into plugins sources to fix the compilation.

Add suitable headers to various plugins (Changes due to recent wayfire refactoring)

---

src/extra-animations/dodge.hpp

- Fix view animations with same or similar center points
- Apply output coordinates to views when testing for intersection
- Don't dodge child windows, only affect those without a parent

extra-animations: dodge: More fixes
